use "D:\data\PreliminaryAnalysis\returns\form16_data_v3_0901.dta"
export delimited id T312002 RefundClaimedBoolean TaxPeriod PeriodBegin PeriodEnd DealerTIN Frequency TurnoverGross TurnoverCentral TurnoverLocal TurnoverAt1 OutputTaxAt1 TurnoverAt5 OutputTaxAt5 TurnoverAt125 OutputTaxAt125 TurnoverAt20 OutputTaxAt20 WCTurnoverAt5 WCOutputTaxAt5 WCTurnoverAt125 WCOutputTaxAt125 ExemptedSales PurchaseOtherGoods OutputTaxBeforeAdjustment AdjustmentOutputTax TotalOutputTax PurchaseCapitalGoods CreditCapitalGoods PurchaseGoodsAt1 CreditGoodsAt1 PurchaseGoodsAt5 CreditGoodsAt5 PurchaseGoodsAt125 CreditGoodsAt125 PurchaseGoodsAt20 CreditGoodsAt20 WCPurchaseAt5 WCCreditAt5 WCPurchaseAt125 WCCreditAt125 CreditOtherGoods TaxCreditBeforeAdjustment AdjustmentTaxCredit TotalTaxCredit NetTax InterestPayable PenaltyPayable TDSCertificates BalancePayable AmountDepositedByDealer AggregateAmountPaid NetBalance BalanceBroughtForward AdjustCSTLiability RefundClaimed BalanceCarriedNextTaxPeriod AccountNumber AccountType MICR BankDetails InterStateSaleCD InterStatePurchaseCD InterStateSaleCE1E2 InterStatePurchaseCE1E2 InterStateExportsAgainstH InterStateImportsAgainstH InterStateExportsAgainstI InterStateExportsAgainstJ InterStateImportsAgainstI InterStateImportsAgainstJ ImportToIndia InterStateSaleOther InterStatePurchaseOther InterStateSaleCapital InterStatePurchaseCapital TotalInterStateSale TotalInterStatePurchase Name Designation Place Date TDSString Receipt2A2B WardName TDSDetails Status ApprovalDate AcknowledgementNumber Year PurchaseUnregisteredDealer ReturnType DieselSale DieselPurchase PurchaseCompositionDealer PurchaseNonCreditableGoods PurchaseRetailInvoice PurchaseTaxFreeGoods LaborCharges LandCharges SaleDelhiFormH WCLabourPurchase PurchaseIneligibleForITC PurchaseDelhiFormH PurchaseCapitalNonCreditGood CarryForwardTaxCredit CSTAdjustmentVAT OutwardStockTransferBranchF InwardStockTransferConsignmentF OwnGoodsTransferredAfterJobF OwnGoodsReceivedAfterJobF OtherDealersGoodsTrJobF OtherDealersGoodsReJobF SaleExemptedGoodsSchedule PurchaseExemptedGoodsSch  HighSeaSale HighSeaPurchase T312202 SourceFile Tin Time Days ReturnCount groupid using "D:\data\PreliminaryAnalysis\returns\form16_data_v3_0901_fewer_columns.csv", quote replace

use "E:\data\PreliminaryAnalysis\returns\form16_data_v5_02222017.dta"
export delimited using "E:\data\PreliminaryAnalysis\returns\form16_data_v5_02222017.csv", quote replace

use "E:\data\annexure_2A2B_quarterly_2013.dta"
export delimited using "E:\data\annexure_2A2B_quarterly_2013.csv", quote replace

use "E:\data\annexure_2A2B_quarterly_2014.dta", clear
export delimited using "E:\data\annexure_2A2B_quarterly_2014.csv", quote replace



use "E:\data\PreliminaryAnalysis\BogusDealers\BogusIdentifiedFromOnlineGovernment.dta", clear
 export delimited using "E:\data\PreliminaryAnalysis\BogusDealers\BogusIdentifiedFromOnlineGovernment.csv", quote replace
